name: my_todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  firebase_storage: ^12.4.7
  flutter_local_notifications: ^19.3.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/vectors/

