// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfC_Ktzaqyw5z43IwXTKQcYXTJo7_Hbvw',
    appId: '1:62732423982:web:e725b3f76eda4cc4d0a0bf',
    messagingSenderId: '62732423982',
    projectId: 'my-todo-cc327',
    authDomain: 'my-todo-cc327.firebaseapp.com',
    storageBucket: 'my-todo-cc327.firebasestorage.app',
    measurementId: 'G-LD0K229BN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqAhApQswK8sRHQOvPRhTpzSiSbw-yjyE',
    appId: '1:62732423982:android:db432bd47826b0a8d0a0bf',
    messagingSenderId: '62732423982',
    projectId: 'my-todo-cc327',
    storageBucket: 'my-todo-cc327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGq46XDQZqrN8t8pSvl0wsxgfKRewh_R0',
    appId: '1:62732423982:ios:a6936f2d34910ac5d0a0bf',
    messagingSenderId: '62732423982',
    projectId: 'my-todo-cc327',
    storageBucket: 'my-todo-cc327.firebasestorage.app',
    iosBundleId: 'com.example.myTodo',
  );
}
